# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1294, 623)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1291, 621))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.rootContainer = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.rootContainer.setContentsMargins(0, 0, 0, 0)
        self.rootContainer.setObjectName("rootContainer")
        self.cameraView = QtWidgets.QGraphicsView(self.horizontalLayoutWidget)
        self.cameraView.setMinimumSize(QtCore.QSize(920, 0))
        self.cameraView.setMaximumSize(QtCore.QSize(557, 16777215))
        self.cameraView.setObjectName("cameraView")
        self.rootContainer.addWidget(self.cameraView)
        self.rightPanel = QtWidgets.QVBoxLayout()
        self.rightPanel.setObjectName("rightPanel")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.sbTime = QtWidgets.QSpinBox(self.groupBox)
        self.sbTime.setGeometry(QtCore.QRect(90, 40, 111, 31))
        self.sbTime.setProperty("value", 4)
        self.sbTime.setObjectName("sbTime")
        self.btnStart = QtWidgets.QPushButton(self.groupBox)
        self.btnStart.setGeometry(QtCore.QRect(230, 40, 121, 31))
        self.btnStart.setObjectName("btnStart")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 50, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.rightPanel.addLayout(self.horizontalLayout_2)
        self.rootContainer.addLayout(self.rightPanel)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HealBone-GaitAnalysis"))
        self.groupBox.setTitle(_translate("MainWindow", "Control Panel"))
        self.btnStart.setText(_translate("MainWindow", "开始步态检测"))
        self.label.setText(_translate("MainWindow", "检测时长"))
