# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainWindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1328, 803)
        MainWindow.setToolButtonStyle(Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QTabWidget.Rounded)
        MainWindow.setDockOptions(QMainWindow.AllowTabbedDocks|QMainWindow.AnimatedDocks)
        self.centralWidget = QWidget(MainWindow)
        self.centralWidget.setObjectName(u"centralWidget")
        self.horizontalLayout = QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.tabWidget = QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.KinectFOV = QWidget()
        self.KinectFOV.setObjectName(u"KinectFOV")
        self.cameraFovView = QGraphicsView(self.KinectFOV)
        self.cameraFovView.setObjectName(u"cameraFovView")
        self.cameraFovView.setGeometry(QRect(0, 0, 731, 513))
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraFovView.sizePolicy().hasHeightForWidth())
        self.cameraFovView.setSizePolicy(sizePolicy)
        self.tabWidget.addTab(self.KinectFOV, "")
        self.KinectIR = QWidget()
        self.KinectIR.setObjectName(u"KinectIR")
        self.cameraIrView = QGraphicsView(self.KinectIR)
        self.cameraIrView.setObjectName(u"cameraIrView")
        self.cameraIrView.setGeometry(QRect(0, 0, 731, 513))
        sizePolicy.setHeightForWidth(self.cameraIrView.sizePolicy().hasHeightForWidth())
        self.cameraIrView.setSizePolicy(sizePolicy)
        self.tabWidget.addTab(self.KinectIR, "")
        self.KinectIRFOV = QWidget()
        self.KinectIRFOV.setObjectName(u"KinectIRFOV")
        self.cameraIrFovView = QGraphicsView(self.KinectIRFOV)
        self.cameraIrFovView.setObjectName(u"cameraIrFovView")
        self.cameraIrFovView.setGeometry(QRect(0, 0, 731, 513))
        sizePolicy.setHeightForWidth(self.cameraIrFovView.sizePolicy().hasHeightForWidth())
        self.cameraIrFovView.setSizePolicy(sizePolicy)
        self.tabWidget.addTab(self.KinectIRFOV, "")

        self.horizontalLayout.addWidget(self.tabWidget)

        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1328, 23))
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.resultsDock = QDockWidget(MainWindow)
        self.resultsDock.setObjectName(u"resultsDock")
        self.resultsDock.setEnabled(True)
        self.resultsDock.setMinimumSize(QSize(258, 143))
        self.resultsDock.setMaximumSize(QSize(640, 524287))
        font = QFont()
        font.setFamily(u"Arial")
        self.resultsDock.setFont(font)
        self.resultsDock.setFeatures(QDockWidget.DockWidgetFloatable|QDockWidget.DockWidgetMovable)
        self.resultsDockContents = QWidget()
        self.resultsDockContents.setObjectName(u"resultsDockContents")
        self.verticalLayout_5 = QVBoxLayout(self.resultsDockContents)
        self.verticalLayout_5.setSpacing(4)
        self.verticalLayout_5.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(1, 0, 1, 1)
        self.groupBox = QGroupBox(self.resultsDockContents)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setEnabled(True)
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy1)
        self.groupBox.setMinimumSize(QSize(256, 0))
        self.btnStart = QPushButton(self.groupBox)
        self.btnStart.setObjectName(u"btnStart")
        self.btnStart.setGeometry(QRect(130, 24, 111, 32))
        self.sbTime = QSpinBox(self.groupBox)
        self.sbTime.setObjectName(u"sbTime")
        self.sbTime.setGeometry(QRect(10, 24, 111, 31))
        self.sbTime.setValue(4)
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 5, 47, 16))
        font1 = QFont()
        font1.setFamily(u"Arial")
        font1.setPointSize(8)
        self.label.setFont(font1)

        self.verticalLayout_5.addWidget(self.groupBox)

        self.resultsDock.setWidget(self.resultsDockContents)
        MainWindow.addDockWidget(Qt.LeftDockWidgetArea, self.resultsDock)
        self.messagesDock = QDockWidget(MainWindow)
        self.messagesDock.setObjectName(u"messagesDock")
        self.messagesDock.setMinimumSize(QSize(91, 101))
        self.messagesDock.setFeatures(QDockWidget.DockWidgetFloatable|QDockWidget.DockWidgetMovable)
        self.messagesDockContents = QWidget()
        self.messagesDockContents.setObjectName(u"messagesDockContents")
        self.verticalLayout_3 = QVBoxLayout(self.messagesDockContents)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(1, 0, 1, 1)
        self.outputText = QPlainTextEdit(self.messagesDockContents)
        self.outputText.setObjectName(u"outputText")
        self.outputText.setFrameShape(QFrame.StyledPanel)
        self.outputText.setFrameShadow(QFrame.Plain)
        self.outputText.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.outputText.setReadOnly(True)

        self.verticalLayout_3.addWidget(self.outputText)

        self.messagesDock.setWidget(self.messagesDockContents)
        MainWindow.addDockWidget(Qt.BottomDockWidgetArea, self.messagesDock)
        self.viewerDock = QDockWidget(MainWindow)
        self.viewerDock.setObjectName(u"viewerDock")
        self.viewerDock.setFeatures(QDockWidget.DockWidgetFloatable|QDockWidget.DockWidgetMovable)
        self.viewerDockContents = QWidget()
        self.viewerDockContents.setObjectName(u"viewerDockContents")
        self.verticalLayout = QVBoxLayout(self.viewerDockContents)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.frame = QFrame(self.viewerDockContents)
        self.frame.setObjectName(u"frame")
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QSize(322, 322))
        self.frame.setAutoFillBackground(False)

        self.verticalLayout.addWidget(self.frame)

        self.viewerDock.setWidget(self.viewerDockContents)
        MainWindow.addDockWidget(Qt.RightDockWidgetArea, self.viewerDock)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"HealBone-GaitAnalysis", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.KinectFOV), QCoreApplication.translate("MainWindow", u"FOV", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.KinectIR), QCoreApplication.translate("MainWindow", u"IR", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.KinectIRFOV), QCoreApplication.translate("MainWindow", u"IR FOV", None))
        self.resultsDock.setWindowTitle(QCoreApplication.translate("MainWindow", u"Gait Control Panel", None))
        self.groupBox.setTitle("")
        self.btnStart.setText(QCoreApplication.translate("MainWindow", u"\u5f00\u59cb\u6b65\u6001\u68c0\u6d4b", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u68c0\u6d4b\u65f6\u957f", None))
        self.messagesDock.setWindowTitle(QCoreApplication.translate("MainWindow", u"Analysis Messages", None))
        self.viewerDock.setWindowTitle(QCoreApplication.translate("MainWindow", u"RealTime Human Skeleton Viewer", None))
    # retranslateUi

